modules:
  - bamboo.zeromq
#TCPSource/tcp:
#  sinks:
#    - zmq1
#SyslogSource/syslog:
#  port: 4515
#  sinks:
#    - zmq1
ExecSource/tail_mysql:
  key: "system"
  command: "tail -f /tmp/test.log"
  sinks:
    - zmq1
StreamSink/stderr:
  fd: stderr
ZMQPullSink/zmq1:
  endpoint: "tcp://127.0.0.1:4203"
ZMQPushSource/zmq2:
  endpoint: "tcp://*:4203"
  identity: zmq2
  bind: true
  sinks:
    - archive
    - stderr
FileSink/archive:
  path: /tmp/logs
  sync: true
